services:
  db:
    image: pgvector/pgvector:0.8.2-pg18
    environment:
      POSTGRES_DB: aisme
      POSTGRES_USER: aisme
      POSTGRES_PASSWORD: aisme
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql

volumes:
  db-data:
