package org.alterbit.aisme.chat.catalog

fun chatModel(
    id: String = "local-ollama-llama",
    displayOrder: Int? = null,
    displayName: String = "Local Ollama Llama",
    description: String? = "Local Ollama model for chat requests.",
    runtime: ChatModelRuntime = ChatModelRuntime.OLLAMA,
    mode: ChatModelMode = ChatModelMode.LOCAL_SERVER,
    availableOffline: Boolean = false,
    availability: ChatModelAvailability = ChatModelAvailability.CONFIGURED,
    baseUrl: String? = "http://localhost:11434",
    modelName: String? = "llama3.2",
    apiKey: String? = null,
    runtimeId: String = runtime.name,
    assetDirectory: String? = null,
    serverExecutablePath: String? = null,
    ggufFile: String? = null,
    contextSize: Int? = null,
    runtimeArguments: List<String> = emptyList(),
): ChatModelDescriptor =
    ChatModelDescriptor(
        id = id,
        displayOrder = displayOrder,
        displayName = displayName,
        description = description,
        runtimeId = runtimeId,
        runtime = runtime,
        mode = mode,
        availableOffline = availableOffline,
        availability = availability,
        baseUrl = baseUrl,
        modelName = modelName,
        apiKey = apiKey,
        assetDirectory = assetDirectory,
        serverExecutablePath = serverExecutablePath,
        ggufFile = ggufFile,
        contextSize = contextSize,
        runtimeArguments = runtimeArguments,
    )
